from scrapers.news import *

NEWS_CLASSES = {
    "CTS": CTS,
    "TSSDNews": TSSDNews,
    "CTWant": CTWant,
    "TaiwanNews":TaiwanNews,
    "TTV":TTV,
    "CTINews": CTINews,
    "HongKongFreePress": HongKongFreePress,
    "MingPaoNews": MingPaoNews,
    "SingTaoDaily": SingTaoDaily,
    "SCMP": SCMP,
    "ChineseNewYorkTimes": ChineseNewYorkTimes,
    "DeutscheWelle": DeutscheWelle,
    "HKFreePress": HKFreePress,
    "WenWeiPo": WenWeiPo,
    "OrientalDailyNews": OrientalDailyNews,
    "TaKungPao": TaKungPao,
    "HK01": HK01,
    "InitiumMedia": InitiumMedia,
    "YahooNews": YahooNews,
    "HKCD": HKCD,
    "TheEpochTimes": TheEpochTimes,
    "NowTV": NowTV,
    "ChineseBBC": ChineseBBC,
    "VOC": VOC,
    "HKCourtNews": HKCourtNews,
    "ICable": ICable,
    "HKGovernmentNews": HKGovernmentNews,
    "OrangeNews": OrangeNews,
    "TheStandard": TheStandard,
    "HKEJ": HKEJ,
    "HKET": HKET,
    "RTHK": RTHK,
    "TheWitness": TheWitness,
    "InMediaHK": InMediaHK,
    "PeopleDaily": PeopleDaily,
    "XinhuaNewsAgency": XinhuaNewsAgency,
    "GlobalTimes": GlobalTimes,
    "CCTV": CCTV,
    "UnitedDailyNews": UnitedDailyNews,
    "LibertyTimesNet": LibertyTimesNet,
    "ChinaTimes": ChinaTimes,
    "CNA": CNA,
    "PTSNews": PTSNews,
    "CTEE": CTEE,
    "MyPeopleVol": MyPeopleVol,
    "TaiwanTimes": TaiwanTimes,
    "ChinaDailyNews": ChinaDailyNews,
    "SETN": SETN,
    "NextAppleNews": NextAppleNews,
    "GVM":GVM,
    "TaroNews":TaroNews,
    "MirrorMedia": MirrorMedia,
    "NowNews": NowNews,
    "StormMedia": StormMedia,
    "TVBS": TVBS,
    "EBCNews": EBCNews,
    "ETtoday": ETtoday,
    "NewTalk": NewTalk,
    "FTV": FTV,
    "FactcheckLab":FactcheckLab,
    "TFCNews":TFCNews,
    "MyGoPenNews":MyGoPenNews
}
# if news_instance.media_name!="FactcheckLab" and news_instance.media_name!="TFCNews" and news_instance.media_name!="MyGoPenNews":

TAIWAN_MEDIA:List[News]=[
    UnitedDailyNews,
    LibertyTimesNet,
    ChinaTimes,
    CNA,
    PTSNews,
    CTEE,
    MyPeopleVol,
    TaiwanTimes,
    SETN,
    NextAppleNews,
    TaroNews,
    TTV,
    MirrorMedia,
    NowNews,
    StormMedia,
    TVBS,
    EBCNews,
    ETtoday,
    NewTalk,
    CTINews,
    FTV,
    TaiwanNews,
    CTWant,
    TSSDNews,
    CTS,
    YahooNews,
    ChineseBBC,
    DeutscheWelle,
    VOC,
    ChineseNewYorkTimes,
    ChinaDailyNews,
    FactcheckLab,
    TFCNews,
    MyGoPenNews
]

# 聯合報,自由時報,中國時報,中央通訊社,工商時報,公視新聞,工商時報,民眾網,台灣時報,中華日報,三立新聞網,蘋果新聞網,台視新聞,鏡週刊,今日新聞,風傳媒,TVBS新聞,東森新聞,ETtoday新聞雲,新頭殼,中天新聞,民視新聞,台灣英文新聞,時報周刊,台灣新生報,華視新聞,雅虎新聞,BBC 中文網,德國之聲中文網,美國之音中文網,紐約時報中文網