from scrapers.news import *

NEWS_CLASSES = {
    "CTS": CTS,
    "TSSDNews": TSSDNews,
    "CTWant": CTWant,
    "TaiwanNews":TaiwanNews,
    "TTV":TTV,
    "CTINews": CTINews,
    "HongKongFreePress": HongKongFreePress,
    "MingPaoNews": MingPaoNews,
    "SingTaoDaily": SingTaoDaily,
    "SCMP": SCMP,
    "ChineseNewYorkTimes": ChineseNewYorkTimes,
    "DeutscheWelle": DeutscheWelle,
    "HKFreePress": HKFreePress,
    "WenWeiPo": WenWeiPo,
    "OrientalDailyNews": OrientalDailyNews,
    "TaKungPao": TaKungPao,
    "HK01": HK01,
    "InitiumMedia": InitiumMedia,
    "YahooNews": YahooNews,
    "HKCD": HKCD,
    "TheEpochTimes": TheEpochTimes,
    "NowTV": NowTV,
    "ChineseBBC": ChineseBBC,
    "VOC": VOC,
    "HKCourtNews": HKCourtNews,
    "ICable": ICable,
    "HKGovernmentNews": HKGovernmentNews,
    "OrangeNews": OrangeNews,
    "TheStandard": TheStandard,
    "HKEJ": HKEJ,
    "HKET": HKET,
    "RTHK": RTHK,
    "TheWitness": TheWitness,
    "InMediaHK": InMediaHK,
    "PeopleDaily": PeopleDaily,
    "XinhuaNewsAgency": XinhuaNewsAgency,
    "GlobalTimes": GlobalTimes,
    "CCTV": CCTV,
    "UnitedDailyNews": UnitedDailyNews,
    "LibertyTimesNet": LibertyTimesNet,
    "ChinaTimes": ChinaTimes,
    "CNA": CNA,
    "TaiwanEconomicTimes": TaiwanEconomicTimes,
    "PTSNews": PTSNews,
    "CTEE": CTEE,
    "MyPeopleVol": MyPeopleVol,
    "TaiwanTimes": TaiwanTimes,
    "ChinaDailyNews": ChinaDailyNews,
    "SETN": SETN,
    "NextAppleNews": NextAppleNews,
    "MirrorMedia": MirrorMedia,
    "NowNews": NowNews,
    "StormMedia": StormMedia,
    "TVBS": TVBS,
    "EBCNews": EBCNews,
    "ETtoday": ETtoday,
    "NewTalk": NewTalk,
    "FTV": FTV,
}

TAIWAN_MEDIA:List[News]=[
    UnitedDailyNews,
    LibertyTimesNet,
    ChinaTimes,
    CNA,
    TaiwanEconomicTimes,
    PTSNews,
    CTEE,
    MyPeopleVol,
    TaiwanTimes,
    ChinaDailyNews,
    SETN,
    NextAppleNews,
    TTV,
    MirrorMedia,
    NowNews,
    StormMedia,
    TVBS,
    EBCNews,
    ETtoday,
    NewTalk,
    CTINews,
    FTV,
    TaiwanNews,
    CTWant,
    TSSDNews,
    CTS,
    YahooNews,
    ChineseBBC,
    DeutscheWelle,
    VOC,
    ChineseNewYorkTimes
]