from enum import Enum

class MediaNameEnum(str, Enum):
    CTS = "CTS"
    TSSDNews = "TSSDNews"
    CTWant = "CTWant"
    TaiwanNews = "TaiwanNews"
    TTV = "TTV"
    CTINews = "CTINews"
    HongKongFreePress = "HongKongFreePress"
    MingPaoNews = "MingPaoNews"
    SingTaoDaily = "SingTaoDaily"
    SCMP = "SCMP"
    ChineseNewYorkTimes = "ChineseNewYorkTimes"
    DeutscheWelle = "DeutscheWelle"
    HKFreePress = "HKFreePress"
    WenWeiPo = "WenWeiPo"
    OrientalDailyNews = "OrientalDailyNews"
    TaKungPao = "TaKungPao"
    HK01 = "HK01"
    InitiumMedia = "InitiumMedia"
    YahooNews = "YahooNews"
    HKCD = "HKCD"
    TheEpochTimes = "TheEpochTimes"
    NowTV = "NowTV"
    ChineseBBC = "ChineseBBC"
    VOC = "VOC"
    HKCourtNews = "HKCourtNews"
    ICable = "ICable"
    HKGovernmentNews = "HKGovernmentNews"
    OrangeNews = "OrangeNews"
    TheStandard = "TheStandard"
    HKEJ = "HKEJ"
    HKET = "HKET"
    RTHK = "RTHK"
    TheWitness = "TheWitness"
    InMediaHK = "InMediaHK"
    PeopleDaily = "PeopleDaily"
    XinhuaNewsAgency = "XinhuaNewsAgency"
    GlobalTimes = "GlobalTimes"
    CCTV = "CCTV"
    UnitedDailyNews = "UnitedDailyNews"
    LibertyTimesNet = "LibertyTimesNet"
    ChinaTimes = "ChinaTimes"
    CNA = "CNA"
    PTSNews = "PTSNews"
    CTEE = "CTEE"
    MyPeopleVol = "MyPeopleVol"
    TaiwanTimes = "TaiwanTimes"
    ChinaDailyNews = "ChinaDailyNews"
    SETN = "SETN"
    NextAppleNews = "NextAppleNews"
    GVM="GVM"
    TaroNews="TaroNews"
    MirrorMedia = "MirrorMedia"
    NowNews = "NowNews"
    StormMedia = "StormMedia"
    TVBS = "TVBS"
    EBCNews = "EBCNews"
    ETtoday = "ETtoday"
    NewTalk = "NewTalk"
    FTV = "FTV"
    TFCNews="TFCNews"
    FactcheckLab="FactcheckLab"
    MyGoPenNews="MyGoPenNews"


class ErrorTypeEnum(str, Enum):
    LLM_ERROR="LLM_ERROR"
    UNMAPPED_MEDIA = "UNMAPPED_MEDIA"
    PARSING_FAILURE = "PARSING_FAILURE"
    PARSING_ERROR = "PARSING_ERROR"
    ZERO_URLS_FETCHED = "ZERO_URLS_FETCHED"
    DATABASE_TIMEOUT = "DATABASE_TIMEOUT"
    OTHERS = "OTHERS"

OriginEnum = Enum(
    'OriginEnum',
    {'native': 'native', **{item.name: item.value for item in MediaNameEnum}},
    type=str
)